# Глобальные опции (Misc Options) пишутся СНАРУЖИ блоков
# Внимание: в доке написано "variable: splash", по дефолту true. Выставляем false без решетки!
splash = false

# Блок для основного монитора eDP-1
wallpaper {
    monitor = eDP-1
    path = /home/sorelle/Wallpapers/5.jpg
    fit_mode = cover
}

# Блок фолбека (дефолтные обои для всех остальных мониторов, если подключишь)
wallpaper {
    monitor = 
    path = /home/sorelle/Wallpapers/3.jpg
    fit_mode = cover
}
