# Основные цвета: приглушенный темно-зеленый травяной и мягкий белый текст
background      #111613
foreground      #cdd1ce

# Шрифт
font_family     JetBrainsMono Nerd Font
font_size       11.0

# Отключаем раздражающий системный писк
enable_audio_bell no
